// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmrMP-TXt4fisqFPOFIozXeLKDkdhnJ58',
    appId: '1:717466346064:web:20abbed2532dea4217a755',
    messagingSenderId: '717466346064',
    projectId: 'dlylalsham-437e6',
    authDomain: 'dlylalsham-437e6.firebaseapp.com',
    storageBucket: 'dlylalsham-437e6.firebasestorage.app',
    measurementId: 'G-LVSHD6Q5GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvGeCJx1PJaIKU3YcglLRARA_CiQSkaO8',
    appId: '1:717466346064:android:09c3242e04d5a62b17a755',
    messagingSenderId: '717466346064',
    projectId: 'dlylalsham-437e6',
    storageBucket: 'dlylalsham-437e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAje6Vtp8vSdu9nnsogL7tQ6xNjFyHsgcs',
    appId: '1:717466346064:ios:9d65808a0b2e90f617a755',
    messagingSenderId: '717466346064',
    projectId: 'dlylalsham-437e6',
    storageBucket: 'dlylalsham-437e6.firebasestorage.app',
    iosBundleId: 'com.example.dalelElsham',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAje6Vtp8vSdu9nnsogL7tQ6xNjFyHsgcs',
    appId: '1:717466346064:ios:9d65808a0b2e90f617a755',
    messagingSenderId: '717466346064',
    projectId: 'dlylalsham-437e6',
    storageBucket: 'dlylalsham-437e6.firebasestorage.app',
    iosBundleId: 'com.example.dalelElsham',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmrMP-TXt4fisqFPOFIozXeLKDkdhnJ58',
    appId: '1:717466346064:web:8d8f09f9eacc437e17a755',
    messagingSenderId: '717466346064',
    projectId: 'dlylalsham-437e6',
    authDomain: 'dlylalsham-437e6.firebaseapp.com',
    storageBucket: 'dlylalsham-437e6.firebasestorage.app',
    measurementId: 'G-9KQ5CTR8GL',
  );

}